In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
df = pd.read_csv("files_for_lab/customer_churn.csv")
df

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [16]:
df['Churn'].replace({'Yes': 1, 'No': 0}, inplace=True)
df['Churn']

0       0
1       0
2       1
3       0
4       1
       ..
7038    0
7039    0
7040    0
7041    1
7042    0
Name: Churn, Length: 7043, dtype: int64

In [18]:
df.Churn.value_counts()

Churn
0    5174
1    1869
Name: count, dtype: int64

In [24]:
y = df.Churn
X = df[['tenure','SeniorCitizen','MonthlyCharges']]

In [26]:
X

      tenure  SeniorCitizen  MonthlyCharges
0          1              0           29.85
1         34              0           56.95
2          2              0           53.85
3         45              0           42.30
4          2              0           70.70
...      ...            ...             ...
7038      24              0           84.80
7039      72              0          103.20
7040      11              0           29.60
7041       4              1           74.40
7042      66              0          105.65

[7043 rows x 3 columns]

In [27]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.25, random_state=0)
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [28]:
from sklearn.metrics import confusion_matrix, classification_report

model = LogisticRegression()
model.fit(X_train, y_train)

pred_train = model.predict(X_train)
pred_test = model.predict(X_test)
print(classification_report(y_test, pred_test))
print(classification_report(y_train, pred_train))

              precision    recall  f1-score   support

           0       0.82      0.90      0.86      1298
           1       0.61      0.46      0.52       463

    accuracy                           0.78      1761
   macro avg       0.72      0.68      0.69      1761
weighted avg       0.77      0.78      0.77      1761

              precision    recall  f1-score   support

           0       0.82      0.91      0.87      3876
           1       0.65      0.47      0.54      1406

    accuracy                           0.79      5282
   macro avg       0.74      0.69      0.71      5282
weighted avg       0.78      0.79      0.78      5282

In [30]:
from imblearn.over_sampling import SMOTE

sm = SMOTE(k_neighbors=3)
X_train_SMOTE, y_train_SMOTE = sm.fit_resample(X_train, y_train)
X_test_SMOTE, y_test_SMOTE = sm.fit_resample(X_test, y_test)

model = LogisticRegression()
model.fit(X_train_SMOTE, y_train_SMOTE)

pred_train_SMOTE = model.predict(X_train_SMOTE)
pred_test_SMOTE = model.predict(X_test_SMOTE)
print(classification_report(y_test_SMOTE, pred_test_SMOTE))
print(classification_report(y_train_SMOTE, pred_train_SMOTE))

              precision    recall  f1-score   support

           0       0.71      0.72      0.71      1298
           1       0.71      0.70      0.71      1298

    accuracy                           0.71      2596
   macro avg       0.71      0.71      0.71      2596
weighted avg       0.71      0.71      0.71      2596

              precision    recall  f1-score   support

           0       0.73      0.73      0.73      3876
           1       0.73      0.73      0.73      3876

    accuracy                           0.73      7752
   macro avg       0.73      0.73      0.73      7752
weighted avg       0.73      0.73      0.73      7752

In [31]:
from imblearn.under_sampling import TomekLinks

dict= {0: 300, 1: 206}
tl = TomekLinks()

X_train_tl, y_train_tl = tl.fit_resample(X_train, y_train)
X_test_tl, y_test_tl = tl.fit_resample(X_test, y_test)

model = LogisticRegression()
model.fit(X_train_tl, y_train_tl)
model.fit(X_test_tl, y_test_tl)

pred_train_tl = model.predict(X_train_tl)
pred_test_tl = model.predict(X_test_tl)
print(classification_report(y_test_tl, pred_test_tl))
print(classification_report(y_train_tl, pred_train_tl))

              precision    recall  f1-score   support

           0       0.82      0.89      0.85      1143
           1       0.66      0.51      0.58       463

    accuracy                           0.78      1606
   macro avg       0.74      0.70      0.72      1606
weighted avg       0.77      0.78      0.77      1606

              precision    recall  f1-score   support

           0       0.83      0.90      0.86      3515
           1       0.68      0.53      0.59      1406

    accuracy                           0.79      4921
   macro avg       0.75      0.71      0.73      4921
weighted avg       0.78      0.79      0.78      4921